Feature/translated stream
dominikdnd/twilio-video-app-react pull request #18
Opened 2021-12-07 21:04 UTC by leolurch

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [AHOYAPPS-0000](https://issues.corp.twilio.com/browse/AHOYAPPS-0000)

### Description

A description of what this PR does.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2022-01-09 18:39 UTC, dominikdnd requested changes

2022-01-09 18:39 UTC, dominikdnd commented on src/components/Buttons/RoundButton.tsx
> +  numberIndicator?: number;
Can't this be just one prop?

2022-01-09 18:39 UTC, dominikdnd commented on src/components/Buttons/ToggleChatButton/ToggleChatButton.tsx
> +      title={langCode === LANGUAGE_CODE.de_DE ? 'Chat Fenster öffnen' : 'Open the chat window'}
For the future: Better to work with i18n translation

2022-01-09 18:39 UTC, dominikdnd commented on src/components/ChatWindow/MessageList/MessageList.tsx
> +        const nextTime = getFormattedTime(langCode, messages[idx + 1]);
Can be undefined if idx + 1 is not existent

2022-01-09 18:39 UTC, dominikdnd commented on src/components/ParticipantTracks/ParticipantTracks.tsx
>    const publications = usePublications(participant);
publications?

2022-01-09 18:39 UTC, dominikdnd commented on src/components/ParticipantTracks/ParticipantTracks.tsx
> +      }
Maybe apply other formatting here

2022-01-09 18:39 UTC, dominikdnd commented on src/components/VideoProvider/index.tsx
> +import { ErrorCallback } from 'types/types';
Better to import from types/error or types/general

2022-01-09 18:39 UTC, dominikdnd commented on src/components/VideoProvider/useScreenShareToggle/useScreenShareToggle.test.tsx
> +import { ErrorCallback } from '../../../types/types';
Better to use absolute paths here: "types/types"

2022-01-09 18:39 UTC, dominikdnd commented on src/index.tsx
> +import './types/types';
Import all types?

2022-01-09 18:39 UTC, dominikdnd commented on src/components/ParticipantTracks/ParticipantTracks.tsx
> +      }
The same as we use for reaction.link, see https://github.com/reaction-link/config-files

2022-01-10 19:00 UTC, leolurch commented on src/components/Buttons/RoundButton.tsx
> +  numberIndicator?: number;
I wanted to separate it explicitly because these two options use different styling and never switch functionality at runtime.

2022-01-12 13:43 UTC, dominikdnd commented on src/components/Buttons/RoundButton.tsx
> +  numberIndicator?: number;
alright

2022-01-12 13:49 UTC, merged